logging:
  level:
    cn.ddos: debug
server:
  port: 8001
spring:
  application:
    name: erp_permissions # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 175.24.22.3:8850 #nacos服务的地址 不要加http

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xhh.ddos-sec.cn:3306/erp?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1234
    # druid
    druid:
      initialSize: 3
      minIdle: 3
      maxActive: 30
      maxWait: 15000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        # allow:
        # login-username: root
        # login-password: 1234
        #禁止那些ip
        # deny:
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # redis
  redis:
    host: xhh.ddos-sec.cn
    password: 1234
    port: 6400
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 0
        max-wait: 2000

#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  login-url: /index.html
  unauthorized-url: /unauthorized.html
  anon-urls:
    - /login/doLogin*
    - /druid/**
    - /swagger-ui.html
    - /webjars/**
    - /swagger-resources/**
    - /v2/**
    - /login/captcha
  logout-url: /login/logout*
  authc-urls:
    - /**

# mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml

#fastdfs设置
fdfs:
  so-timeout: 2500       # 读取时间
  connect-timeout: 5000   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表
    - xhh.ddos-sec.cn:22122
upload:
  base-url: xhh.ddos-sec.cn/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
